<div class="bloc">
   	<div class="petit_haut"></div>
   	<div class="petit_fond"> 
   		<div style="text-align: center">
   			<img src="/images/photo1.png" alt="" />
   		</div> 
   		<p class="texte_bloc">
   			Obtenir 1Mo pour stocker vos données !
   		</p>
   		<a href="#"><img src="/images/lire_suite.png" width="226" height="32" alt="" /></a>
   	</div>
   	<div class="petit_bas"></div>   
</div>

<div class="bloc">
   	<div class="petit_haut"></div>
   	<div class="petit_fond"> 
   		<div style="text-align: center">
   			<img src="/images/photo2.png" alt="" />
   		</div>
   		<p class="texte_bloc">
   			Obtenir 10Mo pour stocker vos données !
   		</p>
   		<a href="#"><img src="/images/lire_suite.png" width="226" height="32" alt="" /></a>
   	</div>
   	<div class="petit_bas"></div>   
</div>

<div class="bloc">
   	<div class="petit_haut"></div>
   	<div class="petit_fond"> 
   		<div style="text-align: center">
   			<img src="/images/photo3.png" alt="" />
   		</div>
	   	<p class="texte_bloc">
	   		Obtenir 100Mo pour stocker vos données !
	   	</p>
   		<a href="#"><img src="/images/lire_suite.png" width="226" height="32" alt="" /></a>
   	</div>
   	<div class="petit_bas"></div>
</div> 