<?php
	if($this->message != null){
		echo "	<div class='message'>".$this->message."</div><br/>";
	}
	if($this->erreur != null){
		echo "	<div class='erreur'>".$this->erreur."</div><br/>";
	}
?>

<div class="hero-unit">
	<h1>Datacenter</h1>
	<p>Premier service de stockage des fichiers en ligne !</p>
	<a href="#" class="btn btn-success btn-large" onclick="$('#inscription').slideToggle(500);">Inscription <i class="icon-chevron-right"></i><i class="icon-chevron-right"></i></a>
</div>

<p><b>Data center permet de stocker toutes vos données sur nos serveur.</b></p><br />

<div class="row">
	<div class="span4">
		<img src="http://lorempixel.com/300/100/technics">
		<p>Optez pour nôtre formule <b>mini</b> à 1 Mo d'espace de stockage !</p>
		<a href="#" class="btn btn-large btn-danger" onclick="$('#inscription').slideToggle(500);setFormula(1);">Souscrire à l'offre <b>mini</b></a>
	</div>
	<div class="span4">
		<img src="http://lorempixel.com/300/100/technics">
		<p>Optez pour nôtre formule <b>basique</b> à 10 Mo d'espace de stockage !</p>
		<a href="#" class="btn btn-large btn-primary" onclick="$('#inscription').slideToggle(500);setFormula(10);">Souscrire à l'offre <b>basique</b></a>
	</div>
	<div class="span4">
		<img src="http://lorempixel.com/300/100/technics">
		<p>Optez pour nôtre formule <b>maxi</b> à 100 Mo d'espace de stockage !</p>
		<a href="#" class="btn btn-large btn-success" onclick="$('#inscription').slideToggle(500);setFormula(100);">Souscrire à l'offre <b>maxi</b></a>
	</div>
</div>