<form method="post" action ="/index/inscription">
	<table>
		<tr>
			<td>Nom :</td>
			<td><input type="text" name="identifiant" /></td>
		</tr>
		<tr>
			<td>Prenom :</td>
			<td><input type="text" name="pwd" /></td>
		</tr>
		<tr>
			<td>Adresse e-mail :</td>
			<td><input type="mail" name="pwd" /></td>
		</tr>
		<tr>
			<td>Mot de passe :</td>
			<td><input type="password" name="pwd" /></td>
		</tr>
		<tr>
			<td>Valider le mot de passe :</td>
			<td><input type="password" name="pwd" /></td>
		</tr>
	</table>
	<input type="submit" name="valider" />
</form>