<?php //echo $this->twitter; ?>

<?php
	if($this->message != ""){
		echo "<div class='message'>".$this->message."</div><br/>";
	} elseif($this->erreur != ""){
		echo "<div class='erreur'>".$this->erreur."</div><br/>";
	}
?>
<div>
	<b><?php echo $this->espaceRestant." Mo d'espace disponible"; ?></b>
</div>
<br>
<?php
	if($this->changerOption){
		echo "	<div id='changementOption'>
					<form method='post' action='/interface/changer-formule/' class='form-inLine well'>";
						if($this->user['formule'] == 100){
							echo "<b>Vous disposez déja de l'espace de stockage maximal ! Merci</b>";
						} elseif($this->user['formule'] == 10) {
							echo $this->changementOption->centMo."<br/>".$this->changementOption->submit;
						} elseif ($this->user['formule'] == 1) {
							echo $this->changementOption->centMo."<br/>".$this->changementOption->dixMo."<br/>".$this->changementOption->submit;
						}
		echo "		</form>
				</div>";
	}
?>
<div id="changerOptionManuel">
	<?php echo "<form method='post' action='/interface/changer-formule/' class='form-inLine well'>";
					if($this->user['formule'] == 100){
						echo "<b>Vous disposez déja de l'espace de stockage maximal ! Merci</b>";
					} elseif($this->user['formule'] == 10) {
						echo $this->changementOption->centMo."<br/>".$this->changementOption->submit;
					} elseif ($this->user['formule'] == 1) {
						echo $this->changementOption->centMo."<br/>".$this->changementOption->dixMo."<br/>".$this->changementOption->submit;
					}
		  echo "</form>"; 
	?>
</div>
<div id='upload'>
	<?php echo $this->upload; ?>
</div>
<div id='newFolder'>
	<?php echo $this->createFolder; ?>
</div>
<input class="btn btn-primary" type="button" value="Upload" onClick="$('#upload').slideToggle(500, function(){if($('#newFolder').css('display')=='block'){$('#newFolder').slideUp(500);}else if($('#changerOptionManuel').css('display')=='block'){$('#changerOptionManuel').slideUp(500);}});"/>
<input class="btn btn-primary" type="button" value="Créer un dossier" onClick="$('#newFolder').slideToggle(500, function(){if($('#upload').css('display')=='block'){$('#upload').slideUp(500);}else if($('#changerOptionManuel').css('display')=='block'){$('#changerOptionManuel').slideUp(500);}});"/>
<input class="btn btn-success" type="button" value="Augmenter mon espace de stockage" onClick="$('#changerOptionManuel').slideToggle(500, function(){if($('#upload').css('display')=='block'){$('#upload').slideUp(500);}else if($('#newFolder').css('display')=='block'){$('#newFolder').slideUp(500);}});"/>
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
</ul>
<?php echo $this->contenu; ?>