<?php
	if($this->message != ""){
		echo "<div class='message'>".$this->message."</div>";
	} elseif($this->erreur != ""){
		echo "<div class='erreur'>".$this->erreur."</div>";
	}
?>
<div>
	<?php echo $this->espaceRestant." Mo d'espace disponnible"; ?>
</div>
<br>
<?php
	if($this->changerOption){
		echo "<div id='changementOption'>".$this->changementOption."</div>";
	}
?>
<div id='upload'>
	<?php echo $this->upload; ?>
</div>
<div id='newFolder'>
	<?php echo $this->createFolder; ?>
</div>
<input type="button" value="Upload" onClick="$('#upload').slideToggle(500, function(){if($('#newFolder').css('display')=='block'){$('#newFolder').slideUp(500);}});"/>
<input type="button" value="Créer un dossier" onClick="$('#newFolder').slideToggle(500, function(){if($('#upload').css('display')=='block'){$('#upload').slideUp(500);}});"/>
</br></br>
<a href="/interface/index/">Home</a>
</br></br>
<?php echo $this->contenu; ?>