<form enctype="multipart/form-data" action="/interface/upload" method="POST">
    <input type="hidden" name="MAX_FILE_SIZE" value="104857600" />
    <input name="fichier" type="file"/>
    <br />
    Dossier de destination : <?php echo $this->dossiers; ?>
   	</br>
    <input type="submit" value="Uploadez le fichier" />
</form>
</br>
<?php
	if(is_array($this->message)){
		foreach ($this->message as $value) {
			echo "<div class='erreur'>".$value."</div></br>";
		}
	} elseif($this->message != "") {
		echo "<div class='message'>".$this->message."</div>";
	}
?>