<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>Administration</title>
		<meta charset="utf-8">
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
		<script charset="utf-8" src="/js/jquery.js"></script>
		<?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css')?>
		<?php echo $this->headLink()->appendStylesheet('/css/admin.css')?>
	</head>
	<body>
		
		<div class="container">
			<div class="navbar navbar-inverse">
				<div class="navbar-inner">
					<a class="brand" href="/">Datacenter</a>
					<form method="post" action="/admin/logout" class="navbar-form pull-right">
						<input type="submit" value="Déconnexion" class="btn btn-danger"/>
					</form>
				</div>
			</div>
		</div>
		
		<div class="container">
			<div id="contenu">
				<?php echo $this -> layout() -> content; ?>
			</div>

			<div id="footer">
		        	Copyright GONCALVES Mickael
		    </div>
		</div>
	</body>
</html>