<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>Interface</title>
		<meta charset="utf-8">
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
		<?php echo $this->headLink()->appendStylesheet('/css/interface.css')?>
	</head>
	<body>
		<div id="conteneur">
			<div id="connexion">
				<form method="post" action="/interface/logout">Bienvenue sur l'interface de gestion de vos fichiers <input type="submit" value="Déconnexion"/></form>
			</div>
			<div id="menu">
				<ul>
					<li><a href="/interface/">Consulter mes fichiers</a></li>
					<li><a href="/interface/add">Déposer des fichiers</a></li>
					<li><a href="/interface/amis">Liste d'amis</a></li>
				</ul>
			</div>
			<div id="contenu">
				<?php echo $this -> layout() -> content; ?>
			</div>
			<div style="clear:both"></div>
			<div id="footer">
				<p>
					copyright GONCALVES Mickael
				</p>
			</div>
		</div>
	</body>
</html>