<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>Data center</title>
		<meta charset="utf-8">
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
		<?php echo $this->headLink()->appendStylesheet('/css/global.css'); ?>
		<script type="text/javascript" src="/js/setFormula.js"></script>
	</head>
	<body>
		<div id="conteneur">
			<div id="connexion">
				<?php echo $this->render('/index/login.phtml') ?>
			</div>
			<div id="header">
				<p>Profitez de nos différentes offres pour stocker vos données !</p>
				<ul>
					<li><a href="#" onClick="setFormula('1')">1 Mo d'espace disque !</a></li>
					<li><a href="#" onClick="setFormula('10');">10 Mo d'espace disque !!</a></li>
					<li><a href="#" onClick="setFormula('100');">100 Mo d'espace disque !!!</a></li>
				</ul>
			</div>
			<div id="contenu">
				<?php echo $this -> layout() -> content; ?>
			</div>
			<div style="clear:both"></div>
			<div id="footer">
				<p>
					copyright GONCALVES Mickael
				</p>
			</div>
		</div>
	</body>
</html>